 name: Windows - Litemanager
 on:
   workflow_dispatch:

  jobs:
    build:
    name: Start Building...
    run-on: windows-latest

    steps:
      - name: Downloading & installing Essentials
        run: |
          Invoke-WebReuest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
        
